export const getLanguageFromExtension = (ext: string): string => {
  const map: Record<string, string> = {
    js: 'javascript',
    jsx: 'jsx',
    ts: 'typescript',
    tsx: 'tsx',
    json: 'json',
    html: 'html',
    htm: 'html',
    css: 'css',
    scss: 'scss',
    sass: 'sass',
    less: 'less',
    py: 'python',
    java: 'java',
    rb: 'ruby',
    cpp: 'cpp',
    c: 'c',
    cs: 'csharp',
    go: 'go',
    rs: 'rust',
    php: 'php',
    swift: 'swift',
    kt: 'kotlin',
    kotlin: 'kotlin',
    scala: 'scala',
    sql: 'sql',
    xml: 'xml',
    yaml: 'yaml',
    yml: 'yaml',
    md: 'markdown',
    markdown: 'markdown',
    txt: 'plaintext',
    log: 'plaintext',
    sh: 'bash',
    bash: 'bash',
    zsh: 'bash',
    dockerfile: 'dockerfile',
    docker: 'dockerfile',
    conf: 'config',
    config: 'config',
    env: 'env',
    ini: 'ini',
    toml: 'toml',
    nginx: 'nginx',
    procfile: 'procfile',
    makefile: 'makefile',
    git: 'git',
    gitignore: 'git',
    GNUmakefile: 'makefile',
    gnufile: 'makefile',
    dockerignore: 'dockerfile',
    envfile: 'env',
  };
  return map[ext] || 'unknown';
};
